// Lessons content — a starter set covering the skills tested in the practice bank.
// Each lesson: teaching content + a 2-question comprehension check.
// skillTags map to the "skill" field used in questions.js, so missed practice-test
// questions can link straight to the matching lesson.

const LESSONS = [

  // ---------------- VERBAL ----------------
  { id:'lv1', section:'verbal', title:'Synonyms & Antonyms', skillTags:['Synonyms','Antonyms'],
    content:`<p>Words can lie to you. Not on purpose — but a word that <em>sounds</em> negative might actually be positive, and a word that <em>sounds</em> related to the answer might mean something totally different. Synonym and antonym questions are really testing whether you know what a word means, or whether you're just guessing from its vibe.</p>
      <p><strong>Key strategy:</strong> before you even glance at the choices, come up with your own one-word or short-phrase definition of the given word. Then go looking for the choice that matches <em>your</em> definition — don't scan for a word that "sounds similar," since test writers love including a decoy that sounds related but means something else entirely.</p>
      <p><strong>Worked example (synonym):</strong> AMIABLE — what does it mean? "Friendly and pleasant to be around." Now scan the choices: Hostile, Good-natured, Nervous, Distant. "Good-natured" matches your own definition directly — that's the answer. Hostile is close to the opposite, and Nervous and Distant aren't related to friendliness at all.</p>
      <p><strong>Worked example (the "sounds negative but isn't" trap):</strong> LACONIC. If you've never seen this word, it <em>sounds</em> like it should mean something bad — maybe "lacking" something, or "sick" (it does share a syllable with a few unpleasant-sounding words, purely by coincidence). It actually means "using very few words, terse." Choices: Talkative, Brief and to-the-point, Confused, Careless. "Brief and to-the-point" is the match — Talkative is close to the opposite, and the other two aren't related at all. The lesson here: sound is not meaning. Never guess a word's definition from how it feels on your tongue.</p>
      <div class="checkin">Stop and check yourself: cover the next paragraph. What's your own definition of the word FRUGAL, before you read on?</div>
      <p>For antonym questions, watch for choices that are actually <em>synonyms</em> of the original word wearing a disguise — that's the single most common trap on this question type.</p>
      <p><strong>Worked example (antonym):</strong> FRUGAL — meaning "careful with money, not wasteful." Choices: Thrifty, Wasteful, Careful, Economical. Thrifty, Careful, and Economical all mean roughly the same as frugal — they're synonym traps, planted specifically to catch someone skimming instead of reading. Only Wasteful is the true opposite.</p>
      <p><strong>Extra example:</strong> DILIGENT (synonym) &rarr; hardworking, since diligent means showing steady, careful effort. And one more antonym for practice: OBSTINATE (meaning stubborn, unwilling to change one's mind) &rarr; the opposite would be something like Flexible or Open-minded, not "Angry" (a decoy that describes a *related* feeling, not the actual opposite meaning).</p>`,
    quiz:[
      { prompt:'Which word means the same as VERBOSE?', correct:'A',
        choices:{ A:{text:'Wordy', explain:'Verbose means using more words than necessary, matching wordy.'}, B:{text:'Silent', explain:'Silent describes no speech at all, not excessive speech.'}, C:{text:'Brief', explain:'Brief is nearly the opposite of verbose.'}, D:{text:'Clear', explain:'Clear describes understandability, not word count.'} } },
      { prompt:'Which word is most nearly opposite to GENEROUS?', correct:'B',
        choices:{ A:{text:'Kind', explain:'Kind is related to generous, not its opposite.'}, B:{text:'Stingy', explain:'Generous means willing to give, so stingy, unwilling to give, is the opposite.'}, C:{text:'Wealthy', explain:'Wealth describes money owned, not willingness to share it.'}, D:{text:'Charitable', explain:'Charitable is closely related to generous, not its opposite.'} } }
    ] },
  { id:'lv2', section:'verbal', title:'Verbal Classification', skillTags:['Verbal classification'],
    content:`<p>These questions give you four words and ask which one doesn't belong. Sounds simple — until you realize the category the other three share is almost always narrower than it first looks, and the test is specifically betting that you'll stop at the first, most obvious grouping you notice.</p>
      <p><strong>Strategy:</strong> figure out what three of the four have in common first, rather than staring at all four trying to spot the "weird" one directly. Common categories include type of animal, type of object, or a shared quality like intensity (quiet vs. loud) or function (things you eat vs. things you cook with).</p>
      <p><strong>Worked example:</strong> Whisper, Shout, Murmur, Mutter. At first glance, all four describe "talking" — so if you stopped there, you'd be stuck with no odd one out at all. Look closer: Whisper, Murmur, and Mutter all describe <em>quiet</em> speech, while Shout is loud. So Shout is the odd one, based on volume, not on the surface fact that all four involve speaking.</p>
      <div class="checkin">Stop and check yourself before reading on: Novel, Poem, Essay, Painting. What do three of these have in common, and which one breaks that pattern?</div>
      <p><strong>Worked example:</strong> Novel, Poem, Essay, Painting. Three of these — Novel, Poem, and Essay — are all forms of <em>writing</em>. Painting is a visual art form, not writing, so it doesn't belong, even though all four could loosely be called "art." Notice the trap: if the category had been "art" instead of "writing," all four would fit, and there'd be no correct answer at all — which is exactly why finding the <em>narrowest</em> shared category matters so much.</p>
      <p><strong>Worked example (a sneakier version of the same trap):</strong> Trumpet, Flute, Clarinet, Violin. All four are musical instruments — too broad a category to give you an odd one out. Narrow it down: Trumpet, Flute, and Clarinet are all played by blowing air through them (they're wind instruments). Violin is played with a bow across strings. So Violin is the odd one, even though every single option here is unmistakably "an instrument."</p>
      <p>Watch for a different trap too: sometimes a word seems different for a shallow, meaningless reason — like starting with a different letter, being a different length, or sounding fancier than the others. None of that matters. The real category is always about meaning or function, never spelling or sound.</p>`,
    quiz:[
      { prompt:'Which does NOT belong: Sparrow, Robin, Eagle, Butterfly?', correct:'D',
        choices:{ A:{text:'Sparrow', explain:'A bird, fitting the shared category.'}, B:{text:'Robin', explain:'Also a bird.'}, C:{text:'Eagle', explain:'Also a bird.'}, D:{text:'Butterfly', explain:'Unlike the others, a butterfly is an insect, not a bird.'} } },
      { prompt:'Which does NOT belong: Joy, Sorrow, Anger, Chair?', correct:'D',
        choices:{ A:{text:'Joy', explain:'An emotion, fitting the shared category.'}, B:{text:'Sorrow', explain:'Also an emotion.'}, C:{text:'Anger', explain:'Also an emotion.'}, D:{text:'Chair', explain:'Unlike the others, a chair is an object, not an emotion.'} } }
    ] },
  { id:'lv3', section:'verbal', title:'Analogies', skillTags:['Analogies'],
    content:`<p>Analogy questions test whether you can identify the exact relationship between a pair of words, then carry that same relationship over to a new pair. The hard part is never finding a choice that's <em>related</em> to the second word — several usually will be. The hard part is finding the one that matches the relationship <em>exactly</em>.</p>
      <p><strong>Strategy:</strong> turn the first pair into a sentence, like "A ___ is a young ___" or "A ___ is used to ___," then plug each answer choice into that same sentence and see which one still sounds natural and true.</p>
      <p><strong>Worked example:</strong> Puppy is to Dog as Cub is to ___. Sentence: "A puppy is a young dog." Applying the pattern: "A cub is a young ___" &rarr; Bear.</p>
      <p><strong>Worked example:</strong> Thermometer is to Temperature as Scale is to ___. Sentence: "A thermometer is used to measure temperature." Applying the pattern: "A scale is used to measure ___" &rarr; Weight. Notice how choices like "kitchen" or "numbers" might seem loosely related to a scale, but neither survives being plugged into the actual sentence — "A scale is used to measure kitchen" doesn't mean anything.</p>
      <div class="checkin">Stop and check yourself: Author is to Book as Composer is to ___. Build your own sentence for the first pair before reading on, then decide what belongs in the blank.</div>
      <p><strong>Worked example (the "reversed relationship" trap):</strong> Author is to Book as Composer is to ___. Sentence: "An author creates a book." Applying the pattern: "A composer creates a ___" &rarr; Song (or Symphony). Here's the trap version of this exact question: if the choices included "Orchestra," it might tempt you, since a composer and an orchestra are obviously connected. But an orchestra <em>performs</em> a composer's work — it doesn't get <em>created</em> the way a book does. Plug it into your sentence to catch this: "A composer creates an orchestra" sounds wrong immediately, because that's backwards from the actual relationship.</p>
      <p><strong>Watch for:</strong> any answer choice that's related to the second word in some general, thematic way but doesn't preserve the <em>exact</em> relationship from the first pair. If your sentence doesn't sound natural — or worse, sounds only true in the reverse direction — with a choice plugged in, it's not the answer, no matter how connected the words feel on the surface.</p>`,
    quiz:[
      { prompt:'Glove is to hand as sock is to ___.', correct:'A',
        choices:{ A:{text:'Foot', explain:'A glove covers a hand; a sock covers a foot, following the same pattern.'}, B:{text:'Shoe', explain:'A shoe is worn over a sock, not the body part it covers.'}, C:{text:'Cold', explain:'A quality, not a body part.'}, D:{text:'Winter', explain:'A season, not a body part.'} } },
      { prompt:'Teacher is to classroom as pilot is to ___.', correct:'B',
        choices:{ A:{text:'Airport', explain:'An airport is a larger location, not the specific workspace, unlike the specific "classroom."'}, B:{text:'Airplane', explain:'A teacher works in a classroom; a pilot works in an airplane, following the same pattern.'}, C:{text:'Passenger', explain:'A passenger is who a pilot transports, not the workspace.'}, D:{text:'Sky', explain:'Too broad — the pattern calls for the specific vehicle, like classroom is specific.'} } }
    ] },
  { id:'lv4', section:'verbal', title:'Syllogisms', skillTags:['Syllogisms'],
    content:`<p>Syllogism questions give you two statements (premises) and ask what must logically follow. The single most important rule: rely only on what is directly stated — no outside knowledge, no assumptions, no "well, that's probably also true."</p>
      <p><strong>Worked example (why outside knowledge is dangerous here):</strong> "All students who study get an A. Patrick didn't study." What can we conclude about Patrick's grade? You might be tempted to say Patrick won't get an A — after all, he didn't do the work. But that assumption reaches outside the given information: we were only ever told about students who <em>do</em> study. We know nothing at all about what happens to students who don't. The correct answer is <strong>no valid conclusion can be drawn</strong>.</p>
      <div class="checkin">Stop and check yourself: does that feel like a strange answer? Most people's gut says Patrick definitely didn't get the A. That gut feeling is exactly the trap — it's using real-world assumption, not the actual logic given.</div>
      <p><strong>Common traps, each with its own worked example:</strong></p>
      <ul>
        <li><strong>Reversing a statement</strong> ("All A are B" does NOT mean "All B are A"). Example: "All roses are flowers" does not mean "All flowers are roses" — tulips and daisies are flowers too, just not roses.</li>
        <li><strong>Assuming full overlap when only "some" is stated.</strong> Example: "Some dogs are brown. All brown animals shed fur." This tells you some dogs shed fur (the brown ones), but it does NOT tell you anything about dogs that aren't brown.</li>
        <li><strong>Concluding something the premises don't actually guarantee.</strong> Example: "All squares are rectangles" does not let you conclude "This rectangle is a square" — plenty of rectangles aren't squares.</li>
      </ul>
      <p><strong>Strategy:</strong> if the premises don't force one specific, unavoidable conclusion, the answer is usually "no valid conclusion can be drawn" or "cannot be determined."</p>
      <p><strong>Full worked example (a valid, direct conclusion):</strong> "All juniors take biology. Sam is a junior." What follows? Since Sam meets the exact condition described (being a junior), and the rule states all juniors take biology, it's guaranteed that Sam takes biology — no assumption needed, just a direct application of the rule.</p>
      <p><strong>3. Converting HSPT statements into conditional statements.</strong> The HSPT rarely hands you a clean "If this, then that." Instead you get sentences like "All students who study get an A," "Only members of the chess club may enter," or "No fish have lungs for breathing air directly." All of these are conditional statements wearing a disguise — and once you translate them, every trick above works exactly the same way.</p>
      <p><strong>"All" statements</strong> translate directly: "All A are B" means "If something is A, then it is B" (that's exactly what we did with Patrick, above). <strong>"No" statements</strong> flip the conclusion to a negative: "No A are B" means "If something is A, then it is not B." Example: "No penguins can fly. Pingu is a penguin." &rarr; If something is a penguin, it cannot fly. Pingu is a penguin, so Pingu cannot fly — direct application, no tricks.</p>
      <p><strong>"Only" statements are where it gets genuinely tricky</strong> — tricky enough to be one of the most commonly missed conversions on the whole test. Most people's gut instinct is to treat "Only A are B" the same as "All A are B." It's not the same — "only" statements actually flip the hypothesis and conclusion from what you'd expect. "Only members of the chess club may enter the tournament" guarantees that entering <em>requires</em> membership — but it never guarantees that every member automatically gets in. So the correct translation is: "If you entered, then you are a member" (entering is the hypothesis, membership is the conclusion — the reverse of most people's first guess).</p>
      <div class="checkin">Stop and check yourself with these two, same setup for both: "Only members of the chess club may enter the tournament." (1) Ravi entered the tournament — what follows? (2) Devon is a member of the chess club — what follows? Answer both before reading on.</div>
      <p>Using our translated conditional ("If entered, then member"): (1) Ravi entered — that's exactly the hypothesis, so the conclusion applies directly: <strong>Ravi is a member.</strong> Valid, guaranteed. (2) Devon is a member — that's the <em>conclusion</em> side, not the hypothesis. Concluding Devon must have entered would mean assuming the converse, which is never guaranteed. <strong>No valid conclusion can be drawn</strong> about whether Devon entered. Same sentence, two completely different outcomes, depending entirely on which piece of information you were handed.</p>
      <p><strong>4. "Some" qualifiers.</strong> "Some A are B" guarantees only that at least one A is B — nothing about which ones, and nothing at all about the rest of A that isn't covered.</p>
      <p><strong>Worked example:</strong> "Some monsters under Timmy's bed are purple. All purple monsters are friendly." The purple monsters under the bed (which exist, since "some" says so) are friendly, by the second rule — so "some monsters under Timmy's bed are friendly" is valid. But "<em>all</em> monsters under Timmy's bed are friendly" overreaches — we know nothing about the non-purple ones. If you ever find yourself concluding "all" from a statement that only gave you "some," stop and double check.</p>
      <p><strong>The sneakiest version of this trap</strong> is when the overreaching conclusion also happens to be true in real life: "Some birds can swim. All penguins are birds. Therefore, some penguins can swim." Tempting, since you already know penguins can swim. But look only at what these two sentences guarantee: nothing connects the specific "some birds" that swim to penguins at all — as far as the logic goes, those swimming birds could be exclusively ducks and swans. <strong>No valid conclusion can be drawn</strong> from these statements alone, even though the conclusion is true in the real world. This is the exact discipline Patrick's example asked of you at the very top of this lesson.</p>`,
    quiz:[
      { prompt:'All cats are felines. All felines are mammals. Therefore:', correct:'A',
        choices:{ A:{text:'All cats are mammals', explain:'Since all cats are felines, and all felines are mammals, all cats must be mammals.'}, B:{text:'All mammals are cats', explain:'This reverses the logic without support.'}, C:{text:'All felines are cats', explain:'This reverses the first statement without support.'}, D:{text:'No conclusion can be drawn', explain:'A conclusion can actually be drawn here.'} } },
      { prompt:'Some students play soccer. All soccer players wear cleats. Therefore:', correct:'B',
        choices:{ A:{text:'All students wear cleats', explain:'Only "some" students play soccer, so this overstates the conclusion.'}, B:{text:'Some students wear cleats', explain:'Since some students play soccer, and all soccer players wear cleats, at least those students wear cleats.'}, C:{text:'No students wear cleats', explain:'This contradicts the given information directly.'}, D:{text:'All cleat-wearers are students', explain:'This reverses the logic — plenty of non-students could wear cleats too.'} } },
      { prompt:'Only members of the chess club may enter the tournament. Maria is not a member of the chess club. Therefore:', correct:'B',
        choices:{ A:{text:'Maria can enter the tournament', explain:'This contradicts the contrapositive of the original statement.'}, B:{text:'Maria cannot enter the tournament', explain:'The contrapositive of "if entered, then member" is "if not a member, then did not enter" — always valid.'}, C:{text:'Maria is secretly a member', explain:'This isn\u2019t supported by anything stated.'}, D:{text:'No valid conclusion can be drawn', explain:'A conclusion can actually be drawn here, via the contrapositive.'} } },
      { prompt:'Some birds can swim. All penguins are birds. Therefore:', correct:'D',
        choices:{ A:{text:'Some penguins can swim', explain:'This is true in real life, but not guaranteed by these two statements alone — the swimming birds and the penguins could be entirely different birds as far as the logic goes.'}, B:{text:'All penguins can swim', explain:'This overstates the first premise, which only says "some" birds swim.'}, C:{text:'No penguins can swim', explain:'This isn\u2019t supported by the statements either.'}, D:{text:'No valid conclusion can be drawn', explain:'The premises don\u2019t connect the swimming birds specifically to penguins.'} } }
    ] },

  // ---------------- QUANTITATIVE ----------------
  { id:'lq1', section:'quant', title:'Number Series', skillTags:['Number series'],
    content:`<p>Number series questions ask you to find the pattern in a sequence and predict the next (or a missing) term. Below are the common pattern types, each with a worked example.</p>
      <p><strong>1. Constant addition or subtraction</strong> — the same amount is added or subtracted every step.<br>
      Example: 20, 17, 14, ___, 8. What's missing? Check the gaps: 20 to 17 is &minus;3, and 17 to 14 is &minus;3. So the pattern subtracts 3 each time. Following the pattern: 14 &minus; 3 = 11, and to check, 11 &minus; 3 = 8, which matches the last term given. The answer is 11.</p>
      <p><strong>2. Constant multiplication or division</strong> — the same factor multiplies or divides each term.<br>
      Example: 3, 6, 12, 24, ___. Each term is double the one before it (3&times;2=6, 6&times;2=12, 12&times;2=24), so the next term is 24&times;2 = 48.</p>
      <p><strong>3. Changing gaps</strong> — the amount added or subtracted itself increases or decreases each step.<br>
      Example: 1, 2, 4, 7, 11, ___. The gaps are +1, +2, +3, +4 — each gap is one more than the last. So the next gap is +5, making the next term 11+5 = 16.</p>
      <div class="checkin">Stop and check yourself before moving on: 30, 29, 27, 24, 20, ___. Find the pattern in the gaps and predict the next term, then keep reading.</div>
      <p>(The gaps here are &minus;1, &minus;2, &minus;3, &minus;4 — each one drop bigger than the last — so the next gap is &minus;5, giving 20 &minus; 5 = 15.)</p>
      <p><strong>4. Alternating operations</strong> — the pattern switches back and forth between two different operations.<br>
      Example: 10, 20, 18, 28, 26, ___. Track each step: 10+10=20, 20&minus;2=18, 18+10=28, 28&minus;2=26. The pattern alternates +10 and &minus;2. Since the last step was &minus;2, the next step is +10, giving 26+10 = 36.</p>
      <p><strong>5. Special sequences</strong> — recognizable patterns like perfect squares or each term being the sum of the two before it (Fibonacci-style).<br>
      Example (perfect squares): 1, 4, 9, 16, ___. These are 1&sup2;, 2&sup2;, 3&sup2;, 4&sup2; — so the next term is 5&sup2; = 25.<br>
      Example (sum of two previous terms): 2, 3, 5, 8, 13, ___. Check: 2+3=5, 3+5=8, 5+8=13. Following the same rule, the next term is 8+13 = 21.</p>
      <p><strong>Strategy:</strong> write out the differences (or ratios) between consecutive terms first — that usually reveals which of these five patterns you're dealing with immediately, before you've spent any real time guessing.</p>`,
    quiz:[
      { prompt:'6, 12, 24, 48, ___', correct:'B',
        choices:{ A:{text:'56', explain:'Doesn\u2019t match doubling.'}, B:{text:'96', explain:'Each term doubles: 48x2=96.'}, C:{text:'72', explain:'Doesn\u2019t match doubling correctly.'}, D:{text:'60', explain:'Doesn\u2019t match doubling.'} } },
      { prompt:'20, 17, 14, 11, ___', correct:'B',
        choices:{ A:{text:'9', explain:'Doesn\u2019t match subtracting 3 each time.'}, B:{text:'8', explain:'Each term subtracts 3: 11-3=8.'}, C:{text:'7', explain:'Overshoots the -3 pattern.'}, D:{text:'10', explain:'Doesn\u2019t match subtracting 3.'} } }
    ] },
  { id:'lq2', section:'quant', title:'Quantitative Comparison', skillTags:['Quantitative comparison'],
    content:`<p>These questions ask you to compare two values (Column A and Column B) and decide which is greater, whether they're equal, or whether it can't be determined.</p>
      <p><strong>Strategy:</strong> convert both values to the same form (both decimals, or both fractions) before comparing. Never compare a fraction to a decimal by eyeballing them — always convert first.</p>
      <p><strong>Worked example (fraction vs. decimal):</strong> Column A = 3/8, Column B = 0.4. Convert 3/8 to a decimal: 3 &divide; 8 = 0.375. Now it's a fair comparison: 0.375 is less than 0.4, so Column B is greater.</p>
      <p><strong>Worked example (exponents):</strong> Column A = 3&sup2;, Column B = 2&sup3;. A bigger base doesn't always mean a bigger result — work both out fully: 3&sup2; = 9 and 2&sup3; = 8. So Column A is greater, even though 2 looks like the "bigger-feeling" exponent.</p>
      <div class="checkin">Stop and check yourself before reading on: Column A = &minus;3, Column B = &minus;5. Which is greater? (Careful — negative numbers trip up more students on this question type than anything else.)</div>
      <p><strong>Worked example (the negative number trap):</strong> Column A = &minus;3, Column B = &minus;5. It's tempting to think "5 is bigger than 3, so Column B must be greater" — but that's comparing the wrong direction entirely. On a number line, &minus;3 sits to the <em>right</em> of &minus;5, meaning &minus;3 is the larger value (it's closer to zero, and less negative). <strong>Column A is greater.</strong> Whenever both values are negative, the number that "looks smaller" (has the smaller digit) is usually the actual winner — the opposite of how positive numbers work.</p>
      <p><strong>Worked example (percentages):</strong> Column A = 20% of 50, Column B = 45% of 20. Calculate each: 20% of 50 = 0.20 &times; 50 = 10. 45% of 20 = 0.45 &times; 20 = 9. Column A is greater.</p>
      <p>Only choose "cannot be determined" when the values actually depend on an unknown variable (like an unlabeled x). If both sides are fixed numbers, as in every example above, a comparison is always possible — don't pick "cannot be determined" just because the math looks complicated or takes a few steps.</p>`,
    quiz:[
      { prompt:'Compare: Column A = 2/3   Column B = 0.65', correct:'A',
        choices:{ A:{text:'Column A is greater', explain:'2/3 is approximately 0.667, which is greater than 0.65.'}, B:{text:'Column B is greater', explain:'0.65 is actually less than 2/3.'}, C:{text:'Equal', explain:'0.667 and 0.65 are not equal.'}, D:{text:'Cannot be determined', explain:'Both are fixed values, so a comparison is possible.'} } },
      { prompt:'Compare: Column A = 4 cubed   Column B = 8 squared', correct:'C',
        choices:{ A:{text:'Column A is greater', explain:'4 cubed is 64, which is not greater than Column B.'}, B:{text:'Column B is greater', explain:'8 squared is also 64, not greater than Column A.'}, C:{text:'Equal', explain:'4 cubed = 64 and 8 squared = 64, so they are equal.'}, D:{text:'Cannot be determined', explain:'Both evaluate to fixed numbers, so a comparison is possible.'} } }
    ] },

  // ---------------- MATHEMATICS ----------------
  { id:'lm1', section:'math', title:'Algebra Basics', skillTags:['Algebra'],
    content:`<p>Algebra questions ask you to solve for an unknown variable, usually x. The core strategy is to isolate the variable by undoing operations in reverse order: first undo addition/subtraction, then multiplication/division, distributing parentheses first if needed.</p>
      <p>Whatever you do to one side of the equation, you must do to the other side too, to keep it balanced — think of an equation like a scale that has to stay level.</p>
      <p><strong>Worked example (no parentheses):</strong> 3x + 5 = 20 &rarr; subtract 5 from both sides (3x = 15) &rarr; divide both sides by 3 (x = 5).</p>
      <p><strong>Worked example (with parentheses):</strong> 2(x + 3) = 16. First distribute the 2: 2x + 6 = 16. Then subtract 6 from both sides: 2x = 10. Finally divide both sides by 2: x = 5.</p>
      <div class="checkin">Stop and check yourself before reading on: &minus;2x + 7 = 15. What's x? (Negative coefficients trip people up — take it slow.)</div>
      <p><strong>Worked example (negative coefficient):</strong> &minus;2x + 7 = 15. Subtract 7 from both sides: &minus;2x = 8. Now divide both sides by &minus;2 — and here's the part people rush past: dividing by a negative number, x = 8 &divide; (&minus;2) = &minus;4. Double-check by plugging it back in: &minus;2 &times; (&minus;4) + 7 = 8 + 7 = 15. It checks out. The lesson: don't panic when x ends up negative — it's a perfectly normal answer, as long as your algebra was done correctly.</p>
      <p><strong>Worked example (variable on both sides):</strong> 4x - 2 = 2x + 10. Get the variables on one side by subtracting 2x from both sides: 2x - 2 = 10. Then add 2 to both sides: 2x = 12. Divide by 2: x = 6.</p>
      <p><strong>Quick sanity check habit:</strong> once you solve for x, plug your answer back into the original equation. It takes ten seconds and catches almost every careless arithmetic slip before it costs you the question.</p>`,
    quiz:[
      { prompt:'Solve for x: 5x - 3 = 17', correct:'B',
        choices:{ A:{text:'3', explain:'Doesn\u2019t match the correct steps.'}, B:{text:'4', explain:'Add 3 to both sides (5x=20), then divide by 5 (x=4).'}, C:{text:'5', explain:'Close, but doesn\u2019t match dividing 20 by 5 correctly.'}, D:{text:'7', explain:'Overshoots the correct value.'} } },
      { prompt:'Simplify: 3(x - 4) + 2x', correct:'A',
        choices:{ A:{text:'5x - 12', explain:'Distribute first: 3x-12+2x, then combine like terms: 5x-12.'}, B:{text:'5x - 4', explain:'This drops part of the distributed constant.'}, C:{text:'3x - 12', explain:'This misses adding the 2x term.'}, D:{text:'5x + 12', explain:'This changes the sign of the constant incorrectly.'} } }
    ] },
  { id:'lm2', section:'math', title:'Percentages & Fractions', skillTags:['Percentages','Fractions'],
    content:`<p>Percentage problems usually ask you to find a portion of a number, or find the original number given a percentage. Convert the percent to a decimal (divide by 100) before multiplying.</p>
      <p><strong>Worked example (find the portion):</strong> 15% of 200 &rarr; 0.15 &times; 200 = 30.</p>
      <p><strong>Worked example (reverse a discount):</strong> A jacket costs $80 after a 20% discount. What was the original price? If $80 is what's left after taking away 20%, then $80 represents 80% of the original price. Divide: 80 &divide; 0.8 = $100.</p>
      <div class="checkin">Stop and check yourself before reading on: a $60 item goes up in price by 25%. What's the new price? (This is the discount problem's evil twin — same idea, opposite direction.)</div>
      <p><strong>Worked example (percent increase):</strong> A $60 item goes up in price by 25%. Unlike a discount, where the final price is a percentage of the original, here the increase gets <em>added</em> on top. Two ways to solve it: find 25% of 60 (0.25 &times; 60 = 15) and add it to the original (60 + 15 = $75), or shortcut it by multiplying directly by 1.25 (60 &times; 1.25 = 75). Same answer either way — $75.</p>
      <p><strong>Worked example ("what percent" questions):</strong> 12 is what percent of 48? Divide the part by the whole, then multiply by 100: (12 &divide; 48) &times; 100 = 25%.</p>
      <p>For fraction addition or subtraction, find a common denominator first — you can't combine fractions with different denominators directly, the same way you can't add "3 apples" and "2 oranges" and call it "5 apples."</p>
      <p><strong>Worked example (fraction subtraction):</strong> 3/4 - 1/6. The common denominator of 4 and 6 is 12: 3/4 = 9/12 and 1/6 = 2/12. So 9/12 - 2/12 = 7/12.</p>`,
    quiz:[
      { prompt:'What is 40% of 90?', correct:'B',
        choices:{ A:{text:'32', explain:'Doesn\u2019t match 0.4x90.'}, B:{text:'36', explain:'0.4 x 90 = 36.'}, C:{text:'40', explain:'Doesn\u2019t match the correct product.'}, D:{text:'45', explain:'Overshoots the correct product.'} } },
      { prompt:'What is 2/5 + 1/4?', correct:'B',
        choices:{ A:{text:'3/9', explain:'Adding numerators and denominators directly isn\u2019t how fractions are added.'}, B:{text:'13/20', explain:'Using a common denominator of 20: 2/5=8/20 and 1/4=5/20, so 8/20+5/20=13/20.'}, C:{text:'3/20', explain:'Doesn\u2019t match the correct sum with a common denominator.'}, D:{text:'1/2', explain:'Close, but doesn\u2019t match the exact fraction sum.'} } }
    ] },
  { id:'lm3', section:'math', title:'Geometry Formulas', skillTags:['Geometry'],
    content:`<p>A handful of formulas cover most HSPT geometry questions. Each one below includes a worked example with numbers plugged in.</p>
      <ul>
        <li><strong>Rectangle:</strong> Area = length &times; width, Perimeter = 2(length + width).<br>
        Example: length 7, width 3 &rarr; Area = 7&times;3 = 21. Perimeter = 2(7+3) = 20.</li>
        <li><strong>Square:</strong> Area = side&sup2;, Perimeter = 4 &times; side.<br>
        Example: side 6 &rarr; Area = 6&sup2; = 36. Perimeter = 4&times;6 = 24.</li>
        <li><strong>Triangle:</strong> Area = 1/2 &times; base &times; height.<br>
        Example: base 10, height 4 &rarr; Area = 0.5 &times; 10 &times; 4 = 20.</li>
        <li><strong>Circle:</strong> Circumference = 2 &times; pi &times; radius, Area = pi &times; radius&sup2;.<br>
        Example: radius 5, pi &asymp; 3.14 &rarr; Circumference = 2&times;3.14&times;5 = 31.4. Area = 3.14&times;5&sup2; = 3.14&times;25 = 78.5.</li>
        <li><strong>Cube:</strong> Volume = side&sup3;.<br>
        Example: side 3 &rarr; Volume = 3&times;3&times;3 = 27.</li>
      </ul>
      <div class="checkin">Stop and check yourself before reading on: a circle has a <em>diameter</em> of 14. What's its circumference? (The formula above uses radius — don't skip a step.)</div>
      <p><strong>Worked example (the radius-vs-diameter trap):</strong> a circle has a diameter of 14. The circumference formula needs the <em>radius</em>, not the diameter — and the radius is always half the diameter. So radius = 14 &divide; 2 = 7, and circumference = 2 &times; 3.14 &times; 7 = 43.96. If you'd mistakenly plugged 14 straight in as the radius, you'd get 2&times;3.14&times;14 = 87.92 — exactly double the real answer. This mix-up is one of the most common careless errors on circle questions, so always double-check whether you were handed a radius or a diameter before you plug in anything.</p>
      <p><strong>Strategy:</strong> identify which formula the question is actually asking for (area vs. perimeter vs. volume vs. circumference) before plugging in numbers — mixing these up is the most common mistake. A quick check: area and volume answers are usually much larger numbers than perimeter or circumference for the same shape, since they involve multiplying more dimensions together.</p>`,
    quiz:[
      { prompt:'What is the area of a triangle with base 8 and height 5?', correct:'B',
        choices:{ A:{text:'13', explain:'That\u2019s the sum of base and height, not area.'}, B:{text:'20', explain:'Area = 0.5 x 8 x 5 = 20.'}, C:{text:'40', explain:'That\u2019s the area of a rectangle with the same dimensions, not a triangle, which is half that.'}, D:{text:'26', explain:'Doesn\u2019t match the triangle area formula.'} } },
      { prompt:'What is the circumference of a circle with radius 10? (use pi \u2248 3.14)', correct:'B',
        choices:{ A:{text:'31.4', explain:'That\u2019s pi x radius, missing the factor of 2.'}, B:{text:'62.8', explain:'Circumference = 2 x pi x radius = 2 x 3.14 x 10 = 62.8.'}, C:{text:'314', explain:'That\u2019s actually the area (pi x radius squared), not circumference.'}, D:{text:'15.7', explain:'That\u2019s half of pi x radius, far short of the full circumference.'} } }
    ] },
  { id:'lm4', section:'math', title:'Word Problems', skillTags:['Word problems'],
    content:`<p>Word problems test whether you can translate a real-world scenario into a math expression. The problem isn't the math itself — it's usually the translation step where students go wrong.</p>
      <ol>
        <li>Identify what the question is actually asking for (the unknown).</li>
        <li>Translate key phrases into operations: "sum" = add, "difference" = subtract, "product" = multiply, "per" = divide.</li>
        <li>Write an equation using a variable for the unknown, then solve.</li>
      </ol>
      <p><strong>Worked example (age problem):</strong> Maria is 3 years older than twice her brother's age. If Maria is 17, how old is her brother? Let b = brother's age. Maria's age = 2b + 3, and we know Maria is 17, so 2b + 3 = 17. Subtract 3: 2b = 14. Divide by 2: b = 7.</p>
      <div class="checkin">Stop and check yourself before reading on: "The product of a number and 4, increased by 3, is 27. What's the number?" Translate it into an equation yourself before you keep reading.</div>
      <p><strong>Worked example (translating "product" and "increased by"):</strong> "The product of a number and 4, increased by 3, is 27." Break the sentence into pieces as you translate: "the product of a number and 4" is 4x (a number, times 4). "Increased by 3" means add 3: 4x + 3. "Is 27" means it equals 27: 4x + 3 = 27. Now solve normally — subtract 3 (4x = 24), divide by 4 (x = 6). The hardest part of this problem was never the algebra; it was correctly turning the sentence into 4x + 3 = 27 in the first place.</p>
      <p><strong>Worked example (consecutive integers):</strong> The sum of three consecutive integers is 72. What is the smallest? Represent them as n, n+1, n+2. Their sum is 3n + 3 = 72. Subtract 3: 3n = 69. Divide by 3: n = 23 (the smallest integer).</p>
      <p><strong>Worked example (rate problem):</strong> A car travels 150 miles in 3 hours. At the same rate, how long would 250 miles take? First find the rate: 150 &divide; 3 = 50 mph. Then divide the new distance by that rate: 250 &divide; 50 = 5 hours.</p>
      <p>For rate problems, remember rate = amount &divide; time — and once you know the rate, you can use it to solve for any related distance or time.</p>`,
    quiz:[
      { prompt:'The sum of two consecutive even integers is 34. What is the larger integer?', correct:'C',
        choices:{ A:{text:'16', explain:'That\u2019s the smaller integer, not the larger one.'}, B:{text:'17', explain:'34/2=17, but consecutive even integers can\u2019t include an odd number like 17.'}, C:{text:'18', explain:'Let n and n+2 be the integers: 2n+2=34, so n=16, meaning the larger integer is 18.'}, D:{text:'19', explain:'Overshoots the correct larger integer.'} } },
      { prompt:'A car travels 150 miles in 3 hours. At the same rate, how long would it take to travel 250 miles?', correct:'B',
        choices:{ A:{text:'4 hours', explain:'Doesn\u2019t match the correct proportional scaling.'}, B:{text:'5 hours', explain:'Rate = 150/3 = 50 mph. Time = 250/50 = 5 hours.'}, C:{text:'6 hours', explain:'Overshoots the correct time.'}, D:{text:'7 hours', explain:'Overshoots the correct time by even more.'} } }
    ] },
  { id:'lm5', section:'math', title:'Exponents & Number Properties', skillTags:['Exponents','Number properties'],
    content:`<p>Exponent expressions like x&sup2; mean multiplying the base by itself the number of times shown by the exponent — not multiplying the base by the exponent. This one mistake (treating 3&sup2; as 3&times;2 instead of 3&times;3) is responsible for more wrong answers on this topic than anything else.</p>
      <p><strong>Worked example:</strong> 3&sup2; means 3 &times; 3 = 9, not 3 &times; 2 = 6. Similarly, 2&sup4; means 2&times;2&times;2&times;2 = 16, not 2&times;4 = 8.</p>
      <div class="checkin">Stop and check yourself before reading on: which is bigger, 5 squared or 3 cubed? Work both out fully before you guess based on which exponent "looks bigger."</div>
      <p><strong>Worked example (why you always have to compute, never guess):</strong> 5&sup2; vs. 3&sup3;. Work both out: 5&sup2; = 25, and 3&sup3; = 27. So 3&sup3; is actually the bigger one, even though 5 is a bigger base than 3 — the exponent (how many times you multiply) matters just as much as the base itself, and there's no shortcut that skips actually doing the multiplication.</p>
      <p>Number properties questions often ask about the <strong>least common multiple</strong> (LCM, the smallest number divisible by both) or the <strong>greatest common factor</strong> (GCF, the largest number that divides both evenly). These sound similar but ask opposite questions — LCM is about multiples going <em>up</em>, GCF is about factors going <em>down</em> — so always double check which one the question is actually asking for.</p>
      <p><strong>Worked example (LCM):</strong> LCM of 4 and 6. List multiples of each: 4, 8, 12, 16... and 6, 12, 18... The smallest number appearing in both lists is 12.</p>
      <p><strong>Worked example (GCF):</strong> GCF of 18 and 24. List the factors of each: 18 &rarr; 1, 2, 3, 6, 9, 18. 24 &rarr; 1, 2, 3, 4, 6, 8, 12, 24. The largest number appearing in both lists is 6.</p>`,
    quiz:[
      { prompt:'What is 4 cubed?', correct:'C',
        choices:{ A:{text:'12', explain:'That treats the exponent as multiplication (4x3), not repeated multiplication.'}, B:{text:'16', explain:'That\u2019s 4 squared, not 4 cubed.'}, C:{text:'64', explain:'4 x 4 x 4 = 64.'}, D:{text:'48', explain:'Doesn\u2019t match the correct repeated multiplication.'} } },
      { prompt:'What is the greatest common factor of 18 and 24?', correct:'B',
        choices:{ A:{text:'3', explain:'3 divides both, but it isn\u2019t the greatest common factor.'}, B:{text:'6', explain:'6 is the largest number that divides both 18 and 24 evenly.'}, C:{text:'9', explain:'9 doesn\u2019t divide 24 evenly.'}, D:{text:'12', explain:'12 doesn\u2019t divide 18 evenly.'} } }
    ] },

  // ---------------- LANGUAGE ----------------
  { id:'ll1', section:'language', title:'Subject-Verb Agreement', skillTags:['Subject-verb agreement'],
    content:`<p>The subject and verb in a sentence must agree in number: singular subjects take singular verbs, plural subjects take plural verbs.</p>
      <p>Watch for tricky singular subjects that seem plural: words like "everyone," "neither," "each," and "either" are grammatically singular, even though they refer to groups of people.</p>
      <p><strong>Worked example:</strong> "Neither of the boys were ready" is incorrect — it should be "Neither of the boys was ready," since "neither" is singular. A helpful trick: mentally cross out the "of the boys" part — "Neither ___ was ready" sounds clearly right, while "Neither ___ were ready" sounds clearly wrong.</p>
      <p><strong>Worked example:</strong> "Each of the students have a locker" is incorrect. Cross out "of the students": "Each ___ have a locker" sounds wrong — it should be "Each of the students has a locker."</p>
      <div class="checkin">Stop and check yourself before reading on: "Either the coach or the players ___ responsible." Is it "is" or "are"? (Hint: this rule is different from everything above — read carefully.)</div>
      <p><strong>Worked example (or/nor takes the closer subject):</strong> "Either the coach or the players ___ responsible." Unlike "and," which combines subjects into a plural, "or" and "nor" make the verb agree with whichever subject is <em>closest</em> to it — not the first one, and not some average of the two. Here, "players" (plural) sits right next to the blank, so the verb should be plural: "Either the coach or the players <strong>are</strong> responsible." Flip the sentence around — "Either the players or the coach ___ responsible" — and now "coach" is closest, so it becomes "is": "Either the players or the coach <strong>is</strong> responsible." Same two subjects, same meaning, different verb, purely because of word order.</p>
      <p><strong>Worked example (compound subjects):</strong> "Peanut butter and jelly is my favorite lunch" — even though "and" usually signals plural, this phrase is treated as one single idea (one meal), so the singular "is" is correct here rather than "are."</p>`,
    quiz:[
      { prompt:'Which sentence is correct?', correct:'B',
        choices:{ A:{text:'Each of the students have a locker.', explain:'Each is singular, so it needs "has," not "have."'}, B:{text:'Each of the students has a locker.', explain:'Each is singular and correctly pairs with the singular verb "has."'}, C:{text:'Each of the student have a locker.', explain:'This is missing the plural "students" and uses an incorrect verb form.'}, D:{text:'Each of the students having a locker.', explain:'This isn\u2019t a complete sentence.'} } },
      { prompt:'Which sentence contains an error?', correct:'B',
        choices:{ A:{text:'The team is practicing today.', explain:'Team is treated as a singular unit here, correctly paired with "is."'}, B:{text:'Everybody needs their own pencil.', explain:'Everybody is grammatically singular, so traditional agreement calls for "his or her" rather than "their."'}, C:{text:'She walks to school every day.', explain:'This correctly uses a singular verb with the singular subject "she."'}, D:{text:'No mistake', explain:'Choice B contains an error under traditional agreement rules.'} } }
    ] },
  { id:'ll2', section:'language', title:'Pronouns: Case & Agreement', skillTags:['Pronoun case','Pronoun agreement'],
    content:`<p>Pronoun questions test two things: <strong>case</strong> (subject pronouns like "I/he/she" vs. object pronouns like "me/him/her") and <strong>agreement</strong> (whether a pronoun matches the number of what it refers to).</p>
      <p>For case, try removing the other person from the sentence: "Give the book to (Sarah and) I" &rarr; "Give the book to I" sounds wrong, confirming it should be "me."</p>
      <p><strong>Worked example:</strong> "Him and me went to the movies." Remove "Him and" and "me and" one at a time: "Me went to the movies" sounds wrong — it should be "I went to the movies." So the correct sentence is "He and I went to the movies."</p>
      <div class="checkin">Stop and check yourself before reading on: "___ do you think is going to win?" Is it "who" or "whom"? Try answering the question with a pronoun first — "<em>He</em> is going to win," not "<em>Him</em> is going to win" — and see if that tells you anything.</div>
      <p><strong>Worked example (who vs. whom):</strong> "Who" is a subject pronoun (like he/she/they); "whom" is an object pronoun (like him/her/them). The test: answer the question using a pronoun, and see which one comes out naturally. "___ do you think is going to win?" &rarr; "<em>He</em> is going to win" (not "him"), so the subject pronoun "who" is correct: "<strong>Who</strong> do you think is going to win?" Compare: "To ___ should I address this letter?" &rarr; "I should address this to <em>him</em>" (not "he"), so the object pronoun "whom" is correct: "To <strong>whom</strong> should I address this letter?"</p>
      <p>For agreement, match singular pronouns to singular nouns (each, everyone, a person), even when "they/their" feels more natural in casual speech.</p>
      <p><strong>Worked example:</strong> "Someone left their umbrella." "Someone" is singular, so traditional grammar calls for "his or her": "Someone left his or her umbrella." Compare this to "Both of the sisters brought their books" — "both" is plural, so "their" is correctly used there.</p>`,
    quiz:[
      { prompt:'Which sentence is correct?', correct:'B',
        choices:{ A:{text:'Him and me went to the movies.', explain:'Both pronouns should be subject pronouns here (he, I), not object pronouns.'}, B:{text:'He and I went to the movies.', explain:'Both "he" and "I" are correctly used as subject pronouns.'}, C:{text:'Him and I went to the movies.', explain:'"Him" should be "he," since it\u2019s part of the subject.'}, D:{text:'He and me went to the movies.', explain:'"Me" should be "I," since it\u2019s part of the subject.'} } },
      { prompt:'Which sentence contains an error?', correct:'A',
        choices:{ A:{text:'Someone left their umbrella.', explain:'Someone is grammatically singular, so traditional agreement calls for "his or her" rather than "their."'}, B:{text:'The dog wagged its tail.', explain:'This correctly uses the singular possessive "its" for the dog.'}, C:{text:'Both of the sisters brought their books.', explain:'"Both" is plural, correctly matching the plural "their."'}, D:{text:'No mistake', explain:'Choice A contains an error under traditional agreement rules.'} } }
    ] },
  { id:'ll3', section:'language', title:'Apostrophes: Contractions vs. Possessives', skillTags:['Contractions vs. possessives','Contractions','Plurals vs. possessives'],
    content:`<p>Apostrophes serve two very different jobs, and mixing them up is one of the most common grammar mistakes:</p>
      <ul>
        <li><strong>Contractions</strong> use an apostrophe to replace missing letters: it's = it is, they're = they are, who's = who is.</li>
        <li><strong>Possessives</strong> show ownership: its, their, whose — notice these possessive forms do NOT use an apostrophe.</li>
      </ul>
      <p><strong>Quick test:</strong> if you can replace the word with the two-word version ("it is," "they are," "who is") and it still makes sense, use the apostrophe version. If not, use the possessive form without one.</p>
      <p><strong>Worked example:</strong> "The bird built it's nest." Test it: "The bird built it is nest" — that doesn't make sense, so the possessive "its" is needed instead: "The bird built its nest."</p>
      <p><strong>Worked example (plurals vs. possessives):</strong> "The two puppy's played together" is incorrect — this isn't showing ownership at all, it just needs the plain plural form: "The two puppies played together." Apostrophes are never used to simply make a word plural.</p>
      <div class="checkin">Stop and check yourself before reading on: how would you write the possessive form of "children" — the toys belonging to the children? Is it "childrens' toys" or "children's toys"?</div>
      <p><strong>Worked example (irregular plural possessives):</strong> "Children" is already plural on its own (no "s" needed, unlike "dogs" or "cats"), which throws people off when it's time to show possession. The rule is still the same as any singular word: add apostrophe-s. So it's "children's toys," not "childrens' toys" — there's no such word as "childrens" to begin with, so there's nothing for that final apostrophe to attach to. Same pattern applies to other irregular plurals: "the women's coats," "the men's schedule," never "womens'" or "mens'."</p>`,
    quiz:[
      { prompt:'Which sentence is correct?', correct:'B',
        choices:{ A:{text:"The bird built it's nest in the tree.", explain:'This should be the possessive "its" (no apostrophe), not the contraction "it\u2019s" (it is).'}, B:{text:'The bird built its nest in the tree.', explain:'"Its" correctly shows possession here without an apostrophe.'}, C:{text:"The bird built its' nest in the tree.", explain:'This misplaces the apostrophe after the s, which isn\u2019t a standard form.'}, D:{text:'The bird built it nest in the tree.', explain:'This is missing the possessive \u2019s entirely.'} } },
      { prompt:'Which sentence contains an error?', correct:'A',
        choices:{ A:{text:"Who's backpack is this?", explain:'This should use the possessive "whose," not the contraction "who\u2019s" (who is).'}, B:{text:'Whose backpack is this?', explain:'This correctly uses the possessive "whose" to ask about ownership.'}, C:{text:'I wonder whose turn it is.', explain:'This also correctly uses the possessive "whose."'}, D:{text:'No mistake', explain:'Choice A contains an error, so this option is incorrect.'} } }
    ] },
  { id:'ll4', section:'language', title:'Punctuation Essentials', skillTags:['Punctuation'],
    content:`<p>Quick question: does <em>"Let's eat, Grandma!"</em> mean the same thing as <em>"Let's eat Grandma!"</em>? One comma is the entire difference between inviting your grandmother to dinner and eating her. That's what punctuation rules are actually for — they're the difference between what you meant and what you said.</p>
      <p><strong>Commas separate items in a list</strong> — and the HSPT expects the comma before "and" (the Oxford comma): "I packed a hat, gloves, and a scarf."</p>
      <p><strong>Commas set off introductory phrases.</strong> "After the movie, we grabbed pizza." The comma marks where the warm-up phrase ends and the main sentence begins.</p>
      <div class="checkin">Stop and check yourself before reading on: does "My sister who lives in Denver is visiting" (no commas) mean the same thing as "My sister, who lives in Denver, is visiting" (with commas)? Think about how many sisters each version implies.</div>
      <p><strong>Commas set off nonessential information — and this can change meaning entirely.</strong> "My sister, who lives in Denver, is visiting" implies one sister (bonus fact: Denver). "My sister who lives in Denver is visiting," with no commas, implies multiple sisters and specifies which one. Same words, almost — completely different meaning.</p>
      <p><strong>Comma splices are the most commonly tested comma error</strong> — joining two complete sentences with only a comma: "The test was hard, I still passed." Three fixes: add a conjunction ("...hard, but I still passed"), use a semicolon ("...hard; I still passed"), or split into two sentences ("...hard. I still passed.").</p>
      <p><strong>Semicolons join two complete sentences on their own, without a conjunction.</strong> Quick test: could each side stand alone as a full sentence? "The gym was closed; we went for a run instead" — yes on both sides, so the semicolon is correct.</p>
      <p><strong>Colons introduce a list or explanation — but only after a complete sentence.</strong> "My favorite foods are: pizza, tacos, and sushi" is actually wrong, since "My favorite foods are" isn't complete on its own. Fix: "I have three favorite foods: pizza, tacos, and sushi," or just drop the colon.</p>
      <p><strong>Worked example:</strong> "The test was hard, I still passed" is a comma splice. Any of the three fixes above corrects it — which one you pick just depends on how connected you want the ideas to feel.</p>`,
    quiz:[
      { prompt:'Which sentence is punctuated correctly?', correct:'B',
        choices:{ A:{text:'I bought apples oranges and bananas.', explain:'This is missing the commas needed to separate the list items.'}, B:{text:'I bought apples, oranges, and bananas.', explain:'Commas correctly separate each item in the list.'}, C:{text:'I bought apples, oranges and bananas,', explain:'This sentence incorrectly ends with a comma instead of a period.'}, D:{text:'I bought, apples oranges and bananas.', explain:'The comma right after "bought" is misplaced.'} } },
      { prompt:"Which sentence fixes this comma splice correctly? Original: \"The lights went out, the whole street went dark.\"", correct:'B',
        choices:{ A:{text:'The lights went out, the whole street went dark.', explain:'This is the original comma splice, still uncorrected.'}, B:{text:'The lights went out; the whole street went dark.', explain:'A semicolon correctly joins these two related complete sentences.'}, C:{text:'The lights went out the whole street went dark.', explain:'This removes the comma but creates a run-on sentence instead.'}, D:{text:'The lights went out. and the whole street went dark.', explain:'A period followed by a lowercase conjunction doesn\u2019t form a proper sentence structure.'} } }
    ] },
  { id:'ll5', section:'language', title:'Sentence Combining', skillTags:['Sentence combining'],
    content:`<p>Sentence combining questions ask you to merge two short sentences into one smooth, grammatically correct sentence. Good combined sentences avoid two problems: run-ons (mashing sentences together with no punctuation) and choppy repetition of the subject.</p>
      <p><strong>Strategy:</strong> look for the logical relationship between the two ideas — cause and effect, sequence, contrast — and choose a connector that reflects it (because, after, but, and, although).</p>
      <p><strong>Worked example (cause and effect):</strong> "It started to rain. We packed up the picnic." &rarr; "Because it started to rain, we packed up the picnic" shows cause and effect clearly.</p>
      <p><strong>Worked example (contrast):</strong> "The hike was exhausting. Everyone agreed it was worth it." &rarr; "Although the hike was exhausting, everyone agreed it was worth it" shows the contrast between the difficulty and the payoff.</p>
      <div class="checkin">Stop and check yourself before reading on: "The power went out. We lit some candles." Would "although" or "because" make more sense as the connector here? Why?</div>
      <p><strong>Worked example (picking the wrong connector is its own kind of error):</strong> "The power went out. We lit some candles." The relationship here is cause and effect — the power outage caused the candle-lighting — so "because" fits: "Because the power went out, we lit some candles." Notice what happens if you grab "although" instead: "Although the power went out, we lit some candles" technically reads as a complete sentence, no run-on, no comma splice — but it's still wrong, because "although" signals a contrast or surprise that isn't actually there. Lighting candles when the power goes out isn't surprising at all; it's the obvious response. The sentence can be grammatically flawless and still fail the question, if the connector doesn't match the actual logical relationship.</p>
      <p><strong>Worked example (sequence):</strong> "She finished her homework. She watched a movie." &rarr; "After she finished her homework, she watched a movie" shows the order the two events happened in.</p>
      <p>Whichever connector you choose, double-check two things: that the combined sentence reads as one smooth idea rather than two sentences awkwardly stuck together, <em>and</em> that the connector you picked actually matches the relationship between the two ideas.</p>`,
    quiz:[
      { prompt:"What is the best way to combine: \"Jake finished his chores. Jake went to the park.\"?", correct:'B',
        choices:{ A:{text:'Jake finished his chores, went to the park.', explain:'This drops the second subject, leaving an incomplete second half.'}, B:{text:'Jake finished his chores and went to the park.', explain:'This smoothly joins the two related actions using "and," avoiding repetition of the subject.'}, C:{text:'Jake finished his chores he went to the park.', explain:'This runs the two sentences together with no connecting word or punctuation.'}, D:{text:'Jake finished his chores; the park.', explain:'The second half after the semicolon isn\u2019t a complete sentence.'} } },
      { prompt:'What is the best way to combine: "The bell rang. Class was over."?', correct:'B',
        choices:{ A:{text:'The bell rang, class was over.', explain:'This joins two complete sentences with only a comma, creating a comma splice.'}, B:{text:'When the bell rang, class was over.', explain:'This correctly uses "when" to show the timing relationship between the two events.'}, C:{text:'The bell rang class was over.', explain:'This runs the two ideas together with no punctuation or connector.'}, D:{text:'The bell rang; over, class was.', explain:'This awkwardly reorders the words in a way that doesn\u2019t read naturally.'} } }
    ] },
  { id:'ll6', section:'language', title:'Capitalization Rules', skillTags:['Capitalization'],
    content:`<p>Capitalize proper nouns (specific names of people, places, organizations) and the first word of every sentence. Do NOT capitalize common nouns used generally, including most seasons (summer, winter) and general relation words (my uncle, her mom) when used generally rather than as part of a name.</p>
      <p><strong>Worked example:</strong> "I visited Paris last summer" — Paris is capitalized (a specific place), summer is not (a season, not a proper noun).</p>
      <p><strong>Worked example:</strong> "My uncle Joe lives in Texas" — uncle is lowercase (a general relation word used with "my"), Joe is capitalized (a specific name), and Texas is capitalized (a specific state).</p>
      <div class="checkin">Stop and check yourself before reading on: "We drove south for three hours" vs. "Many people are moving to the South for warmer winters." Should "south" be capitalized in both, neither, or just one? Think about what job the word is doing in each sentence.</div>
      <p><strong>Worked example (direction vs. region name):</strong> "We drove south for three hours" keeps "south" lowercase, because it's just describing a direction of travel — the same job as "left" or "downhill." But "Many people are moving to the South for warmer winters" capitalizes "South," because here it names an actual region (the southern United States, as a place), functioning almost like a proper noun. Same four letters, two different jobs — only one of them earns a capital letter.</p>
      <p><strong>Worked example (school subjects vs. proper nouns):</strong> "She studies history and math at Lincoln High School" — history and math are general subject names and stay lowercase, while Lincoln High School is a specific, named institution and gets capitalized. Note that languages are the exception to the subject rule: "She studies French and history" — French is capitalized because it's also the name of a nationality/language, not because it's a class subject.</p>`,
    quiz:[
      { prompt:'Which sentence is capitalized correctly?', correct:'C',
        choices:{ A:{text:'We drove through Texas in the Spring.', explain:'Spring is a season and shouldn\u2019t be capitalized here.'}, B:{text:'We drove through texas in the spring.', explain:'Texas is a proper noun (a state) and should be capitalized.'}, C:{text:'We drove through Texas in the spring.', explain:'Texas is correctly capitalized as a proper noun, and spring is correctly lowercase as a season.'}, D:{text:'we drove through Texas in the Spring.', explain:'The sentence-starting word should be capitalized.'} } },
      { prompt:'Which sentence is capitalized correctly?', correct:'B',
        choices:{ A:{text:'She studies History and Math at Lincoln High School.', explain:'History and math are general subjects and shouldn\u2019t be capitalized here.'}, B:{text:'She studies history and math at Lincoln High School.', explain:'Lincoln High School is a proper noun and correctly capitalized, while the general subjects history and math are correctly lowercase.'}, C:{text:'She studies history and math at lincoln high school.', explain:'Lincoln High School is a proper noun and should be capitalized.'}, D:{text:'she studies History and Math at Lincoln High School.', explain:'The sentence-starting word should be capitalized.'} } }
    ] },

  // ---------------- READING ----------------
  { id:'lr1', section:'reading', title:'Finding the Main Idea', skillTags:['Main idea'],
    content:`<p>Main idea questions ask what a passage is "primarily about" or ask for the "best summary." The main idea is usually broader than any single detail, but narrower than an overly broad generalization.</p>
      <p><strong>Strategy:</strong> after reading, ask "what is every paragraph working together to explain or show?" Eliminate choices that describe only one small detail (too narrow) or bring in outside information the passage never discusses (too broad or off-topic).</p>
      <p><strong>Sample passage:</strong></p>
      <p style="background:var(--tint);padding:10px 12px;border-radius:8px">"When the local library announced it would close its doors after fifty years, the town's reaction surprised even the librarians. Dozens of former students wrote letters describing quiet afternoons spent studying there. A group of teenagers organized a fundraiser within a week. The mayor's office received more calls about the library than about any other issue that year. In the end, the library stayed open, funded largely by donations from people who hadn't visited in years but couldn't imagine the town without it."</p>
      <p><strong>Walkthrough:</strong> Start by noticing what each sentence contributes. Sentence 1 sets up the announcement. Sentences 2–4 all describe different forms of community response — letters, a fundraiser, phone calls. Sentence 5 shows the outcome: the library survives because of that community reaction.</p>
      <p>Now compare some possible answer choices:</p>
      <ul>
        <li><em>"A library announces a fundraiser"</em> — too narrow. This only covers one sentence, not the whole passage.</li>
        <li><em>"Libraries are important to communities everywhere"</em> — too broad. This passage is about one specific town's library, not libraries in general.</li>
        <li><em>"A town rallies to save its library"</em> — this fits. It captures the announcement, the range of community responses, and the outcome, without adding anything the passage doesn't support.</li>
      </ul>
      <p>Notice that the correct answer doesn't just repeat one detail (like the fundraiser) — it names the pattern that connects all the details together.</p>
      <div class="checkin">Stop and check yourself with a shorter passage before moving to the quiz: "Marco had failed his driving test twice before, both times freezing up during parallel parking. On his third attempt, he took a breath, remembered his instructor's advice to go slowly, and pulled off a perfect park on the first try." What's this passage primarily about — and what would be "too narrow," and what would be "too broad," as wrong answers?</div>
      <p>Here's the reasoning: "too narrow" would be something like "Marco parallel parks a car" — true, but it ignores the failed attempts and what changed. "Too broad" would be something like "Learning to drive takes practice" — that pulls in a general life lesson the passage never actually states. The answer that fits: "Marco overcomes a driving test skill he'd previously struggled with." It captures the struggle, the change in approach, and the successful outcome — the whole arc, no more and no less.</p>`,
    quiz:[
      { prompt:'A passage describes three different ways plants adapt to survive in the desert. What is the passage primarily about?', correct:'B',
        choices:{ A:{text:"A specific desert plant's history", explain:'Too narrow — the passage discusses multiple adaptations generally, not one plant\u2019s history.'}, B:{text:'How plants adapt to desert conditions', explain:'This matches the passage\u2019s focus on multiple survival adaptations.'}, C:{text:'The dangers of desert travel', explain:'Danger isn\u2019t mentioned in this description.'}, D:{text:'How to grow desert plants at home', explain:'Growing plants at home isn\u2019t what the passage discusses.'} } },
      { prompt:'A passage opens by describing a rainstorm, then follows a family as they evacuate and later rebuild their home. What is the best summary?', correct:'B',
        choices:{ A:{text:'A story about a rainstorm', explain:'Too narrow — this ignores most of the passage\u2019s content about the family\u2019s experience.'}, B:{text:'A family responds to a disaster and rebuilds', explain:'This captures the full arc of the passage: the storm, the response, and the rebuilding.'}, C:{text:'A guide to storm safety', explain:'The passage tells a story, not a safety guide.'}, D:{text:'A history of flooding in the region', explain:'No broader regional history is mentioned.'} } }
    ] },
  { id:'lr2', section:'reading', title:'Understanding Detail Questions', skillTags:['Detail'],
    content:`<p>Detail questions ask about specific facts stated directly in the passage — "according to the passage..." Unlike inference questions, the answer is usually stated word-for-word or very close to it in the text.</p>
      <p><strong>Strategy:</strong> go back and skim for the specific detail rather than relying on memory — detail questions often include a trap answer that mixes up two different facts mentioned nearby in the passage.</p>
      <p><strong>Sample passage:</strong></p>
      <p style="background:var(--tint);padding:10px 12px;border-radius:8px">"The lighthouse at Point Arden was built in 1887 after three ships wrecked on the rocks below in a single stormy winter. Standing 92 feet tall, it was operated by a single keeper who lived in a small cottage beside the tower. The light itself could be seen from up to 20 miles out at sea, thanks to a rotating lens imported from France."</p>
      <p><strong>Sample question:</strong> According to the passage, how far out could the lighthouse's light be seen?</p>
      <p><strong>Walkthrough:</strong> Don't rely on memory here — go back to the text. The passage states the light "could be seen from up to 20 miles out at sea." Notice the passage also mentions other numbers nearby: 1887 (the year built), 92 feet (the height), and 20 miles (the visibility distance). A trap answer might swap these — for instance, offering "92 miles" by mixing up the height with the visibility distance. Always match the specific number to the specific fact it describes.</p>
      <div class="checkin">Stop and check yourself: "The recipe, passed down from her grandmother, called for two cups of flour, a full stick of butter, and exactly forty-five minutes in the oven." If a question asked how long the recipe needed to bake, what wrong answer would you expect as a trap, based on the other numbers nearby?</div>
      <p>A likely trap answer would swap in "two" (the cups of flour) instead of "forty-five minutes" — or combine numbers that don't belong together, like "two hours." The actual detail is baked directly into the sentence: forty-five minutes. Detail questions almost never require outside calculation or guessing — the exact answer is sitting in the text, and your only job is finding the right piece of it.</p>`,
    quiz:[
      { prompt:'A passage states: "The bridge, completed in 1932, spans nearly two miles across the bay." According to the passage, when was the bridge completed?', correct:'B',
        choices:{ A:{text:'1923', explain:'This transposes the digits of the correct year.'}, B:{text:'1932', explain:'The passage states directly that the bridge was completed in 1932.'}, C:{text:'1942', explain:'This isn\u2019t the year given in the passage.'}, D:{text:'Two miles', explain:'This is the length of the bridge, not the year it was completed.'} } },
      { prompt:'A passage states: "Unlike her older brother, who preferred quiet reading, Mia loved loud, energetic games." According to the passage, what did Mia\u2019s brother prefer?', correct:'B',
        choices:{ A:{text:'Loud games', explain:'This describes Mia\u2019s preference, not her brother\u2019s.'}, B:{text:'Quiet reading', explain:'The passage states directly that the brother preferred quiet reading.'}, C:{text:'Energetic activities', explain:'This describes Mia, not her brother.'}, D:{text:'Neither reading nor games', explain:'The passage does state a clear preference for the brother — quiet reading.'} } }
    ] },
  { id:'lr3', section:'reading', title:'Vocabulary in Context', skillTags:['Vocabulary in context'],
    content:`<p>These questions ask what a word "most nearly means" as it's used in the passage — not necessarily the word's most common dictionary definition. Context matters more than familiarity with the word.</p>
      <p><strong>Strategy:</strong> cover up the word and reread the sentence, then ask "what word would make sense here?" Compare your own guess to the answer choices, and watch for choices that define the word correctly in a different context, but don't fit this one.</p>
      <p><strong>Sample passage:</strong></p>
      <p style="background:var(--tint);padding:10px 12px;border-radius:8px">"After the third rejection letter, most writers would have given up. But Elaine was undaunted, sending out query after query until an editor finally said yes. Her persistence, more than her talent alone, is what eventually got her published."</p>
      <p><strong>Sample question:</strong> As used in the passage, the word "undaunted" most nearly means:</p>
      <p><strong>Walkthrough:</strong> Cover up "undaunted" and reread: "But Elaine was ___, sending out query after query until an editor finally said yes." The sentence contrasts Elaine with "most writers [who] would have given up" — so whatever word goes in the blank should mean something like "not discouraged" or "not giving up." Now check the choices: "Not discouraged" fits directly. "Confused" or "Excited" might describe a writer in some context, but neither matches the contrast the sentence sets up between giving up and continuing. "Successful" describes an outcome, not the quality that led to it. The context — not the word's difficulty — points to the answer.</p>
      <div class="checkin">Stop and check yourself: "The critic's review was notorious among local restaurant owners, who dreaded seeing her walk through their door." Before reading further, guess what "notorious" means here, using only the context — not any dictionary definition you might already know.</div>
      <p>Here's the twist this word teaches: "notorious" sounds almost neutral or even a little impressive at first glance, similar to "famous." But context here — restaurant owners <em>dreading</em> her — tells you it actually means "famous for something negative or unwelcome," not just "well-known." A choice like "widely admired" would be a classic trap, since it matches "famous" in a general sense but completely misses the negative context the sentence sets up. This is exactly why covering the word and reading the sentence around it matters more than any assumption about what the word "should" mean.</p>`,
    quiz:[
      { prompt:'In the sentence "The old bridge was so decrepit that engineers closed it to traffic," the word "decrepit" most nearly means:', correct:'B',
        choices:{ A:{text:'Beautiful', explain:'This contradicts the context — the bridge was closed, suggesting a problem, not beauty.'}, B:{text:'Worn down and unsafe', explain:'The context (closed to traffic) suggests the bridge was in poor, unsafe condition.'}, C:{text:'Newly built', explain:'This contradicts being old and needing closure.'}, D:{text:'Extremely long', explain:'Length isn\u2019t suggested anywhere in the sentence.'} } },
      { prompt:'In the sentence "Her buoyant mood lifted everyone else in the room," the word "buoyant" most nearly means:', correct:'A',
        choices:{ A:{text:'Cheerful', explain:'The context (lifting others\u2019 spirits) suggests a cheerful, upbeat mood.'}, B:{text:'Heavy', explain:'This contradicts the light, uplifting quality suggested by the sentence.'}, C:{text:'Silent', explain:'Silence isn\u2019t related to affecting others\u2019 mood positively.'}, D:{text:'Confused', explain:'Confusion doesn\u2019t match the positive effect described.'} } }
    ] },
  { id:'lr4', section:'reading', title:'Making Inferences', skillTags:['Inference'],
    content:`<p>Inference questions ask what can be reasonably concluded from the passage, even though it isn't stated directly. The correct answer must be strongly supported by details in the passage — not just a guess or outside assumption.</p>
      <p><strong>Strategy:</strong> look for the answer choice that follows logically from what IS stated, without adding new information the passage never mentions. If a choice requires assuming something the passage doesn't support, it's likely a trap.</p>
      <p><strong>Sample passage:</strong></p>
      <p style="background:var(--tint);padding:10px 12px;border-radius:8px">"Every evening at exactly six o'clock, old Mr. Halloway set two plates at his kitchen table, though he had lived alone since his wife passed away three years earlier. He would talk through dinner as if she were still across the table, then quietly clear both plates when he finished."</p>
      <p><strong>Sample question:</strong> It can be inferred from the passage that Mr. Halloway:</p>
      <p><strong>Walkthrough:</strong> The passage never directly states how Mr. Halloway feels — that's exactly what makes this an inference question rather than a detail question. But look at what it does show: setting two plates, talking through dinner "as if she were still across the table," and doing this every evening, years after her passing. These details, taken together, support a specific and reasonable conclusion: he still deeply misses his late wife and keeps her present through this ritual. A trap answer might claim he "believes she is still alive" — but the passage says he acts "as if" she were there, which signals he knows she isn't, while still holding onto the routine out of grief and memory. The correct inference stays close to what the details actually support, rather than exaggerating them.</p>
      <div class="checkin">Stop and check yourself: "Before the coach even finished announcing the starting lineup, Deja was already lacing up her cleats." What can reasonably be inferred about Deja — and what would be an inference that goes a step too far?</div>
      <p>A solid inference: Deja expected (or hoped) to be named a starter, and was eager and ready to play. A step-too-far inference would be something like "Deja is the best player on the team" — the passage never compares her to teammates or mentions skill level at all, it only shows her eagerness and readiness. The safe move on inference questions is always to stop exactly where the evidence stops, even if a bigger conclusion feels tempting.</p>`,
    quiz:[
      { prompt:'A passage describes a scientist checking her data three times before publishing her results. It can be inferred that the scientist is:', correct:'B',
        choices:{ A:{text:'Careless', explain:'This contradicts the behavior described — checking data multiple times suggests the opposite of carelessness.'}, B:{text:'Careful and thorough', explain:'Checking her work three times suggests a careful, thorough approach.'}, C:{text:'Uncertain about her career', explain:'Career uncertainty isn\u2019t suggested by this behavior.'}, D:{text:'New to research', explain:'Experience level isn\u2019t indicated by this detail alone.'} } },
      { prompt:'A passage describes a boy who packs an umbrella, boots, and a raincoat before leaving for school, even though the sky looks clear. It can be inferred that the boy:', correct:'B',
        choices:{ A:{text:'Dislikes rain', explain:'Disliking rain doesn\u2019t explain why he specifically prepared for it today.'}, B:{text:'Checked a weather forecast predicting rain', explain:'Packing rain gear despite a clear sky suggests he has outside information, like a forecast, predicting rain later.'}, C:{text:'Is forgetful', explain:'Forgetfulness doesn\u2019t explain deliberately packing multiple rain items.'}, D:{text:'Enjoys wearing raincoats', explain:'Nothing suggests he simply enjoys wearing raincoats for their own sake.'} } }
    ] }
];
