// Original, style-matched HSPT practice questions — not reproductions of any real exam.
// This is a starter bank (~40 questions). Add more objects to each array the same shape
// to grow it — the test engine in index.html doesn't need to change.

const PASSAGES = {
  p1: `Honeybees communicate the location of food sources to other members of their hive through a movement known as the waggle dance. By moving in a figure-eight pattern and vibrating its body, a bee can indicate both the direction and distance of a flower patch relative to the sun. Scientists have found that the angle of the dance corresponds to the angle between the sun and the food source, while the duration of the waggle portion indicates how far away the source lies. This remarkable form of communication allows a hive to efficiently direct large numbers of foragers to the most productive locations without any single bee needing to guide the others directly.`,
  p2: `Elena had practiced the same eight measures for nearly an hour, her bow arm aching and her patience thinning. Her teacher, however, showed no sign of ending the lesson. "Again," he said simply, not unkindly, but with the quiet certainty of someone who has taught this passage a hundred times before. Elena set her jaw, lifted the violin, and began once more. This time, on the fifth measure, something shifted — the note rang clear and full, exactly as it was meant to. Her teacher's expression did not change, but he nodded once. It was enough.`
};

const QUESTIONS = {

  verbal: [
    { id:'v1', skill:'Synonyms', prompt:'Choose the word that means the same as CANDID.',
      choices:{A:'Dishonest',B:'Frank',C:'Timid',D:'Elaborate'}, correct:'B',
      wrongTip:'"Candid" has nothing to do with elaborate detail or timidity — those are unrelated meanings that just sound plausible.',
      rightReasoning:'Candid means openly honest and straightforward, which matches "frank" most closely.' },
    { id:'v2', skill:'Antonyms', prompt:'Choose the word most nearly opposite to FRUGAL.',
      choices:{A:'Thrifty',B:'Wasteful',C:'Modest',D:'Careful'}, correct:'B',
      wrongTip:'"Thrifty" and "careful" are actually synonyms of frugal, not opposites — a common trap on antonym questions.',
      rightReasoning:'Frugal means careful with money or resources, so its opposite is spending carelessly — wasteful.' },
    { id:'v3', skill:'Verbal classification', prompt:'Which word does NOT belong with the others?',
      choices:{A:'Salmon',B:'Trout',C:'Bass',D:'Dolphin'}, correct:'D',
      wrongTip:'All four are aquatic animals, which is why this feels tricky — but the category being tested is narrower than "lives in water."',
      rightReasoning:'Salmon, trout, and bass are all fish. A dolphin is a mammal, so it belongs to a different category.' },
    { id:'v4', skill:'Syllogisms', prompt:'All poets are dreamers. Some dreamers are painters. Therefore:',
      choices:{A:'All poets are painters',B:'Some painters are poets',C:'No valid conclusion can be drawn',D:'All painters are dreamers'}, correct:'C',
      wrongTip:'It feels like a connection should exist between poets and painters, but the second statement only guarantees an overlap between dreamers and painters — not which dreamers.',
      rightReasoning:'The painters mentioned might be entirely different dreamers than the poets. Nothing forces overlap between poets and painters specifically.' },
    { id:'v5', skill:'Analogies', prompt:'Puppy is to dog as cub is to ___.',
      choices:{A:'Forest',B:'Bear',C:'Den',D:'Baby'}, correct:'B',
      wrongTip:'"Den" and "forest" describe where a cub might live, but the relationship being tested is young animal to adult animal, not habitat.',
      rightReasoning:'A puppy is a young dog, so by the same pattern, a cub is a young bear.' },
    { id:'v6', skill:'Verbal classification', prompt:'Which word does NOT belong with the others?',
      choices:{A:'Whisper',B:'Shout',C:'Murmur',D:'Mutter'}, correct:'B',
      wrongTip:'All four describe ways of speaking, which is the surface similarity — but volume is the actual sorting category here.',
      rightReasoning:'Whisper, murmur, and mutter all describe quiet speech. Shout is the only loud one, so it is the odd one out.' },
    { id:'v7', skill:'Syllogisms', prompt:'No fish are mammals. All whales are mammals. Therefore:',
      choices:{A:'No whales are fish',B:'All whales are fish',C:'Some whales are fish',D:'No conclusion can be drawn'}, correct:'A',
      wrongTip:'It can feel unsafe to draw a firm "no" conclusion, but the first statement rules out any overlap between the two groups entirely.',
      rightReasoning:'Since no fish are mammals, and whales are mammals, whales cannot also be fish.' },
    { id:'v8', skill:'Synonyms', prompt:'Choose the word that means the same as METICULOUS.',
      choices:{A:'Careless',B:'Thorough',C:'Hasty',D:'Confused'}, correct:'B',
      wrongTip:'Meticulous describes extreme care with detail — the opposite of careless or hasty, which are common wrong answers here.',
      rightReasoning:'Meticulous means showing great attention to detail, which lines up closest with "thorough."' }
  ],

  quant: [
    { id:'q1', skill:'Number series', prompt:'2, 5, 11, 23, 47, ___',
      choices:{A:'71',B:'83',C:'95',D:'94'}, correct:'C',
      wrongTip:'A common mistake is adding a fixed amount each time, but this series is not a simple addition pattern.',
      rightReasoning:'Each number is double the previous number plus 1 (2×2+1=5, 5×2+1=11, 11×2+1=23, 23×2+1=47), so the next term is 47×2+1 = 95.' },
    { id:'q2', skill:'Number series', prompt:'3, 6, 12, 24, ___',
      choices:{A:'30',B:'36',C:'48',D:'42'}, correct:'C',
      wrongTip:'Adding 6 each time matches the first two gaps but breaks down after that — always test a pattern against every pair in the series.',
      rightReasoning:'Each number doubles the one before it, so the next term is 24 × 2 = 48.' },
    { id:'q3', skill:'Quantitative comparison', prompt:'Compare: Column A = 3/4  Column B = 0.7',
      choices:{A:'Column A is greater',B:'Column B is greater',C:'The two columns are equal',D:'Cannot be determined'}, correct:'A',
      wrongTip:'0.7 looks close to 3/4, which is exactly what makes this comparison worth double-checking rather than guessing.',
      rightReasoning:'3/4 equals 0.75, which is greater than 0.7, so Column A is greater.' },
    { id:'q4', skill:'Quantitative comparison', prompt:'Compare: Column A = 5² Column B = 2⁵',
      choices:{A:'Column A is greater',B:'Column B is greater',C:'The two columns are equal',D:'Cannot be determined'}, correct:'B',
      wrongTip:'It is tempting to assume the "5" makes Column A bigger, but exponents grow the base that is repeated, not the base that looks larger.',
      rightReasoning:'5² = 25 and 2⁵ = 32, so Column B is greater.' },
    { id:'q5', skill:'Number series', prompt:'1, 4, 9, 16, 25, ___',
      choices:{A:'30',B:'32',C:'36',D:'34'}, correct:'C',
      wrongTip:'The gaps between terms (3, 5, 7, 9...) increase by 2 each time — spotting that pattern is faster than guessing from the numbers alone.',
      rightReasoning:'These are consecutive perfect squares (1², 2², 3², 4², 5²), so the next term is 6² = 36.' },
    { id:'q6', skill:'Number series', prompt:'100, 90, 81, 73, ___',
      choices:{A:'66',B:'64',C:'68',D:'70'}, correct:'A',
      wrongTip:'Subtracting the same amount each time (like 9 or 10) matches only the first step or two — check that the gap itself is changing.',
      rightReasoning:'The amount subtracted decreases by 1 each time (−10, −9, −8, −7), so the next step is −7, giving 73 − 7 = 66.' },
    { id:'q7', skill:'Quantitative comparison', prompt:'Compare: Column A = 40% of 60  Column B = 25% of 90',
      choices:{A:'Column A is greater',B:'Column B is greater',C:'The two columns are equal',D:'Cannot be determined'}, correct:'A',
      wrongTip:'The larger percentage in Column B (versus the smaller number in A) can make this feel closer than it is — actually compute both.',
      rightReasoning:'40% of 60 is 24, and 25% of 90 is 22.5, so Column A is greater.' },
    { id:'q8', skill:'Number series', prompt:'5, 10, 8, 16, 14, 28, ___',
      choices:{A:'26',B:'56',C:'30',D:'24'}, correct:'A',
      wrongTip:'It is easy to assume the pattern is "always multiply by 2" since that appears often here, but the series alternates between two operations.',
      rightReasoning:'The pattern alternates ×2 and −2 (5×2=10, 10−2=8, 8×2=16, 16−2=14, 14×2=28), so the next step is 28−2 = 26.' }
  ],

  math: [
    { id:'m1', skill:'Algebra', prompt:'If 3x + 5 = 20, what is x?',
      choices:{A:'3',B:'5',C:'15',D:'25'}, correct:'B',
      wrongTip:'Forgetting to subtract 5 from both sides before dividing is the most common slip on this type of problem.',
      rightReasoning:'Subtract 5 from both sides to get 3x = 15, then divide by 3 to get x = 5.' },
    { id:'m2', skill:'Percentages', prompt:'What is 15% of 200?',
      choices:{A:'15',B:'20',C:'30',D:'35'}, correct:'C',
      wrongTip:'Confusing "15% of 200" with "15 more than 200 divided somehow" leads to answers that are off by a factor.',
      rightReasoning:'15% equals 0.15. Multiplying 0.15 × 200 = 30.' },
    { id:'m3', skill:'Geometry', prompt:'A rectangle has a length of 8 and a width of 5. What is its area?',
      choices:{A:'13',B:'26',C:'40',D:'45'}, correct:'C',
      wrongTip:'Adding the length and width instead of multiplying gives the perimeter-related number, not the area.',
      rightReasoning:'Area of a rectangle is length × width, so 8 × 5 = 40.' },
    { id:'m4', skill:'Algebra', prompt:'Simplify: 4(x + 3) − 2x',
      choices:{A:'2x + 12',B:'2x + 3',C:'6x + 12',D:'2x + 7'}, correct:'A',
      wrongTip:'Forgetting to distribute the 4 to both terms inside the parentheses is the usual mistake here.',
      rightReasoning:'Distribute first: 4x + 12 − 2x, then combine like terms: 2x + 12.' },
    { id:'m5', skill:'Word problems', prompt:'The sum of three consecutive integers is 72. What is the smallest of the three?',
      choices:{A:'22',B:'23',C:'24',D:'25'}, correct:'B',
      wrongTip:'Dividing 72 by 3 gives the middle integer (24), not the smallest — a subtle but common misread.',
      rightReasoning:'Let the integers be n, n+1, n+2. Their sum is 3n+3 = 72, so n = 23, the smallest integer.' },
    { id:'m6', skill:'Geometry', prompt:'What is the perimeter of a square with a side length of 9?',
      choices:{A:'18',B:'27',C:'36',D:'81'}, correct:'C',
      wrongTip:'81 is the square\'s area (9×9), not its perimeter — a common mix-up between the two formulas.',
      rightReasoning:'Perimeter of a square is 4 × side length, so 4 × 9 = 36.' },
    { id:'m7', skill:'Word problems', prompt:'A train travels 60 miles in 1.5 hours. What is its average speed?',
      choices:{A:'30 mph',B:'40 mph',C:'45 mph',D:'90 mph'}, correct:'B',
      wrongTip:'Multiplying instead of dividing distance by time is the usual source of the wrong answer here.',
      rightReasoning:'Speed = distance ÷ time, so 60 ÷ 1.5 = 40 mph.' },
    { id:'m8', skill:'Exponents', prompt:'What is the value of 2³ + 3²?',
      choices:{A:'12',B:'13',C:'17',D:'36'}, correct:'C',
      wrongTip:'Multiplying the base by the exponent (like 2×3) instead of repeated multiplication (2×2×2) gives a much smaller, incorrect value.',
      rightReasoning:'2³ = 8 and 3² = 9. Adding them gives 8 + 9 = 17.' }
  ],

  language: [
    { id:'l1', skill:'Subject-verb agreement', prompt:'Which sentence contains an error?',
      choices:{A:'Neither of the boys were ready.',B:'She and I went to the store.',C:'The books are on the shelf.',D:'No mistake'}, correct:'A',
      wrongTip:'"Neither" feels plural because it refers to two boys, but grammatically it takes a singular verb.',
      rightReasoning:'"Neither" is singular, so it should pair with "was," not "were": "Neither of the boys was ready."' },
    { id:'l2', skill:'Punctuation', prompt:'Which sentence is punctuated correctly?',
      choices:{A:"Its a beautiful day, isnt it?",B:"It's a beautiful day, isn't it?",C:"Its' a beautiful day, isn't it.",D:"It's a beautiful, day isn't it?"}, correct:'B',
      wrongTip:'"Its" without an apostrophe means possession, but this sentence needs the contraction "it is," which requires "it\'s."',
      rightReasoning:'Both contractions ("it\'s" and "isn\'t") need apostrophes, and a question needs a question mark — B has all three correct.' },
    { id:'l3', skill:'Pronoun case', prompt:'Which sentence contains an error?',
      choices:{A:'Me and him went fishing.',B:'He and I went fishing.',C:'She and they went fishing.',D:'No mistake'}, correct:'A',
      wrongTip:'Try each pronoun alone: "Me went fishing" sounds wrong immediately, which is the tell that the subject pronoun is needed instead.',
      rightReasoning:'As subjects of the sentence, the correct pronouns are "he and I," not "me and him."' },
    { id:'l4', skill:'Sentence combining', prompt:'What is the best way to combine these two sentences? "The dog barked. The dog was hungry."',
      choices:{A:'The dog barked, it was hungry.',B:'The dog, being hungry, barked.',C:'The dog barked being hungry.',D:'The dog barked; hungry.'}, correct:'B',
      wrongTip:'Option A creates a run-on sentence by joining two full sentences with only a comma.',
      rightReasoning:'Option B correctly turns the second idea into a descriptive phrase attached smoothly to the main sentence.' },
    { id:'l5', skill:'Capitalization', prompt:'Which sentence is capitalized correctly?',
      choices:{A:'I visited paris last Summer.',B:'I visited Paris last summer.',C:'i visited Paris last Summer.',D:'I Visited Paris Last Summer.'}, correct:'B',
      wrongTip:'Seasons like "summer" are not capitalized, even though they can feel like proper nouns.',
      rightReasoning:'"Paris" is a proper noun and must be capitalized; "summer" is not a proper noun and should stay lowercase.' },
    { id:'l6', skill:'Pronoun agreement', prompt:'Which sentence contains an error?',
      choices:{A:'Everyone should bring their own lunch.',B:'Each student must bring his or her book.',C:'The team celebrated its victory.',D:'No mistake'}, correct:'A',
      wrongTip:'This usage is common in everyday speech, which is exactly why it is worth double-checking on a formal grammar test.',
      rightReasoning:'"Everyone" is grammatically singular, so traditional agreement calls for a singular pronoun like "his or her" rather than "their."' },
    { id:'l7', skill:'Punctuation', prompt:'Which sentence is punctuated correctly?',
      choices:{A:'I have three pets: a cat a dog and a fish.',B:'I have three pets: a cat, a dog, and a fish.',C:'I have three pets, a cat, a dog, and a fish.',D:'I have three pets a cat, a dog and a fish.'}, correct:'B',
      wrongTip:'A list introduced by a colon still needs commas separating each item — the colon alone is not enough.',
      rightReasoning:'B correctly uses a colon to introduce the list, with commas separating each item in the series.' },
    { id:'l8', skill:'Subject-verb agreement', prompt:'Which sentence contains an error?',
      choices:{A:"She don't like broccoli.",B:"He doesn't like peas.",C:"They don't like carrots.",D:'No mistake'}, correct:'A',
      wrongTip:'"Don\'t" is common in casual speech with singular subjects, but it does not agree grammatically with "she."',
      rightReasoning:'"She" is singular and third-person, so it needs "doesn\'t," not "don\'t."' }
  ],

  reading: [
    { id:'r1', passage:'p1', skill:'Main idea', prompt:'This passage is primarily about:',
      choices:{A:'The diet of honeybees',B:'How honeybees communicate location information',C:'The dangers facing honeybee populations',D:'How bees make honey'}, correct:'B',
      wrongTip:'The passage never discusses diet, danger, or honey-making — those are plausible bee-related topics that simply are not what this text covers.',
      rightReasoning:'Every sentence in the passage builds toward explaining the waggle dance as a communication method, which is the main idea.' },
    { id:'r2', passage:'p1', skill:'Detail', prompt:'According to the passage, the duration of the waggle indicates:',
      choices:{A:'The direction of the food',B:'The size of the flower patch',C:'How far away the food source is',D:'The number of bees needed'}, correct:'C',
      wrongTip:'Direction is controlled by the angle of the dance, not its duration — mixing up these two details is an easy trap.',
      rightReasoning:'The passage states directly that "the duration of the waggle portion indicates how far away the source lies."' },
    { id:'r3', passage:'p1', skill:'Vocabulary in context', prompt:"As used in the passage, the word 'forager' most nearly means:",
      choices:{A:'A bee that guards the hive',B:'A bee that searches for food',C:'A queen bee',D:'A predator of bees'}, correct:'B',
      wrongTip:'Guard bees and queen bees are real roles in a hive, which makes them tempting distractors — but neither matches how the word is used here.',
      rightReasoning:'The passage describes foragers being directed to "productive locations," meaning bees that go out to search for food.' },
    { id:'r4', passage:'p1', skill:'Inference', prompt:'It can be inferred from the passage that the waggle dance is important because it:',
      choices:{A:'Entertains other bees',B:'Allows bees to communicate without direct guidance',C:'Helps bees avoid predators',D:'Is used only when the hive is threatened'}, correct:'B',
      wrongTip:'Nothing in the passage discusses predators or threats — those ideas are not supported by the text at all.',
      rightReasoning:'The passage explains that the dance lets a hive direct foragers "without any single bee needing to guide the others directly," supporting answer B.' },
    { id:'r5', passage:'p2', skill:'Inference', prompt:"The teacher's response at the end of the passage suggests that he:",
      choices:{A:'Was disappointed in Elena',B:'Recognized her improvement without excessive praise',C:'Had not been listening',D:'Wanted her to stop practicing'}, correct:'B',
      wrongTip:'A single quiet nod can look like a lack of reaction, but read alongside the rest of the passage, it reads as understated approval, not indifference.',
      rightReasoning:'The nod comes right after Elena finally plays the passage correctly, and the passage calls it "enough" — a quiet sign of recognition.' },
    { id:'r6', passage:'p2', skill:'Main idea', prompt:"Elena's mood at the beginning of the passage can best be described as:",
      choices:{A:'Excited',B:'Frustrated',C:'Confident',D:'Indifferent'}, correct:'B',
      wrongTip:'Nothing suggests excitement or confidence at the start — the passage describes an aching arm and thinning patience instead.',
      rightReasoning:'The passage describes her "bow arm aching and her patience thinning," both signs of frustration.' },
    { id:'r7', passage:'p2', skill:'Vocabulary in context', prompt:"The phrase 'quiet certainty' suggests that the teacher:",
      choices:{A:'Was unsure of what to do next',B:'Was calm and confident in his teaching method',C:'Was angry with Elena',D:'Doubted Elena\'s ability'}, correct:'B',
      wrongTip:'"Quiet" might suggest hesitation on its own, but paired with "certainty," it points the opposite direction — calm confidence, not doubt.',
      rightReasoning:'The passage explains this certainty comes from "someone who has taught this passage a hundred times before," showing calm experience rather than doubt.' },
    { id:'r8', passage:'p2', skill:'Main idea', prompt:'What is the best summary of this passage?',
      choices:{A:'A teacher ends a lesson early.',B:'A student struggles but eventually improves with practice.',C:'A student decides to quit violin.',D:'A teacher criticizes a student harshly.'}, correct:'B',
      wrongTip:'The passage never shows the teacher criticizing Elena or the lesson ending early — both add events that are not in the text.',
      rightReasoning:'The passage moves from struggle and fatigue to a moment of improvement on the fifth measure, which B captures accurately.' }
  ]
};
